# Generated by Django 6.0.4 on 2026-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.IntegerField(unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#1a1a2e', max_length=7)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
